AWSTemplateFormatVersion: '2010-09-09'
Description: Tsundzukani Mokgalaka. EC2 instance provision to be used for CircleCI runner.

Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-minimal-kernel-default-x86_64'

Resources:
    EC2Instance:
      Type: 'AWS::EC2::Instance'
      Properties:
          SecurityGroupIds:
            - !Ref InstanceSecurityGroup
          KeyName: tsuKey
          ImageId: !Ref LatestAmiId
          InstanceType: t2.micro
          SubnetId: 
            Fn::ImportValue: !Sub '${EnvironmentName}-PUB1-SN'
          Tags:
            - Key: Name
              Value: BastionHost

    InstanceSecurityGroup:
        Type: 'AWS::EC2::SecurityGroup'
        Properties:
          GroupDescription: Enable SSH access via port 22
          SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort: '22'
              ToPort: '22'
              CidrIp: 0.0.0.0/0
