Description: >
    Tsundzukani Mokgalaka.
    This creates an EKS cluster on the created VPC.



Resources:
    EKSClusterRole:
        Type: AWS::IAM::Role
        Properties:
          RoleName: EKSClusterRole
          AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Principal:
                  Service:
                    - eks.amazonaws.com
                Action:
                  - sts:AssumeRole
          ManagedPolicyArns:
            - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy