Description: >
    Tsundzukani Mokgalaka.
    This creates an EKS cluster on the created VPC.

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

Resources:
    EKSClusterRole:
        Type: AWS::IAM::Role
        Properties:
          RoleName: EKSClusterRole
          AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Principal:
                  Service:
                    - eks.amazonaws.com
                Action:
                  - sts:AssumeRole
          ManagedPolicyArns:
            - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

    EKSClusterSecGroup:
      Type: AWS::EC2::SecurityGroup
      DependsOn: !Sub "${EnvironmentName}-VPCID"
      Properties:
        GroupDescription: Allow http to our hosts
        VpcId:
          Fn::ImportValue: !Sub "${EnvironmentName}-VPCID"
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0

    EKSCluster:
      Type: AWS::EKS::Cluster
      Properties:
        Name: Capstone_Cluster
        Version: "1.20"
        RoleArn: !GetAtt EKSClusterRole.Arn
        ResourcesVpcConfig:
          SecurityGroupIds:
            - Ref: EKSClusterSecGroup
          SubnetIds:
            - Fn::ImportValue: !Sub ${EnvironmentName}-PUB1-SN
            - Fn::ImportValue: !Sub ${EnvironmentName}-PUB2-SN
          EndpointPublicAccess: false
          EndpointPrivateAccess: true
          PublicAccessCidrs: [ "1.1.1.2/32" ]
        Logging:
          ClusterLogging:
            EnabledTypes:
              - Type: api
              - Type: audit
        Tags:
          - Key: "Name"
            Value: "tsu_EKSCluster"