apiVersion: v1
kind: Service
metadata:
  name: capstone-project-service
spec:
  type: NodePort
  selector:
    app: capstone-project-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080